// Code generated by `just contracts-gen` from contracts/director-envelope.schema.json; DO NOT EDIT.
// The canonical schema lives in ArcavenAE/marvel (see contracts/PINNED.md).

///Intentional agent speech carried over the bus, peer to peer including the human. This is an A2A v1.0 compatible profile: the fields here map onto A2A v1.0 message semantics (the FIPA-ACL performative subset maps to A2A message intent), and codegen emits Go and Rust types plus validators from this one schema so the bound consumers cannot drift. Bound consumers: marvel (Go) and beadle (Rust). See contracts/README.md for the A2A mapping and the codegen targets. Time and UUID fields carry both a format annotation and an always-enforced pattern, so validation does not depend on the validator running in format-assertion mode.
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct DirectorEnvelope {
    pub authority: DirectorEnvelopeAuthority,
    pub content: DirectorEnvelopeContent,
    ///Reply chain. On the first message of a chain it equals message_id.
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub conversation_id: ::std::option::Option<::std::string::String>,
    ///Work-item thread across many messages. The loop guard keys on it (correlation_id plus performative plus recipient within a cool-down).
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub correlation_id: ::std::option::Option<::std::string::String>,
    ///Optional RFC3339 queue TTL; a stale control message dies rather than acting late.
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub expires_at: ::std::option::Option<::chrono::DateTime<::chrono::offset::Utc>>,
    ///Optional. The message_id this answers.
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub in_reply_to: ::std::option::Option<DirectorEnvelopeInReplyTo>,
    ///ULID: sortable, unique. Consumers dedupe on this (delivery is at least once).
    pub message_id: DirectorEnvelopeMessageId,
    pub performative: DirectorEnvelopePerformative,
    pub recipient: DirectorEnvelopeRecipient,
    ///Optional RFC3339 expectation; drives escalation.
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub reply_by: ::std::option::Option<::chrono::DateTime<::chrono::offset::Utc>>,
    ///Envelope schema version. Integer per the session-029 rule.
    pub schema_version: i64,
    pub sender: DirectorEnvelopeSender,
    pub sent_at: ::chrono::DateTime<::chrono::offset::Utc>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub trace: ::std::option::Option<DirectorEnvelopeTrace>,
}
///`DirectorEnvelopeAuthority`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct DirectorEnvelopeAuthority {
    ///The authority-bearing seat, or null (the common case).
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub seat: ::std::option::Option<DirectorEnvelopeAuthoritySeat>,
    ///Relayed authority is provably weaker than direct (finding-151). none carries no authority.
    pub strength: DirectorEnvelopeAuthorityStrength,
}
///`DirectorEnvelopeAuthoritySeat`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct DirectorEnvelopeAuthoritySeat {
    pub epoch: i64,
    pub key: ::std::string::String,
    ///The seat role, same closed class as an address role segment (R-76).
    pub role: DirectorEnvelopeAuthoritySeatRole,
}
///The seat role, same closed class as an address role segment (R-76).
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct DirectorEnvelopeAuthoritySeatRole(::std::string::String);
impl ::std::ops::Deref for DirectorEnvelopeAuthoritySeatRole {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<DirectorEnvelopeAuthoritySeatRole> for ::std::string::String {
    fn from(value: DirectorEnvelopeAuthoritySeatRole) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for DirectorEnvelopeAuthoritySeatRole {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> = ::std::sync::LazyLock::new(||
        { ::regress::Regex::new("^[a-z0-9][a-z0-9-]{0,31}$").unwrap() });
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^[a-z0-9][a-z0-9-]{0,31}$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for DirectorEnvelopeAuthoritySeatRole {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String>
for DirectorEnvelopeAuthoritySeatRole {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for DirectorEnvelopeAuthoritySeatRole {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///Relayed authority is provably weaker than direct (finding-151). none carries no authority.
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd
)]
pub enum DirectorEnvelopeAuthorityStrength {
    #[serde(rename = "direct")]
    Direct,
    #[serde(rename = "relayed")]
    Relayed,
    #[serde(rename = "none")]
    None,
}
impl ::std::fmt::Display for DirectorEnvelopeAuthorityStrength {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Direct => f.write_str("direct"),
            Self::Relayed => f.write_str("relayed"),
            Self::None => f.write_str("none"),
        }
    }
}
impl ::std::str::FromStr for DirectorEnvelopeAuthorityStrength {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "direct" => Ok(Self::Direct),
            "relayed" => Ok(Self::Relayed),
            "none" => Ok(Self::None),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for DirectorEnvelopeAuthorityStrength {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String>
for DirectorEnvelopeAuthorityStrength {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///`DirectorEnvelopeContent`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct DirectorEnvelopeContent {
    ///The payload for this content type. Bounded; use refs for anything large.
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub data: ::std::option::Option<::serde_json::Value>,
    ///Pointers, not payload: bd:, finding:, file:, url:, pr:.
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub refs: ::std::vec::Vec<::std::string::String>,
    #[serde(rename = "type")]
    pub type_: DirectorEnvelopeContentType,
}
///`DirectorEnvelopeContentType`
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd
)]
pub enum DirectorEnvelopeContentType {
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "task")]
    Task,
    #[serde(rename = "result")]
    Result,
    #[serde(rename = "signal")]
    Signal,
    #[serde(rename = "pointer")]
    Pointer,
}
impl ::std::fmt::Display for DirectorEnvelopeContentType {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Text => f.write_str("text"),
            Self::Task => f.write_str("task"),
            Self::Result => f.write_str("result"),
            Self::Signal => f.write_str("signal"),
            Self::Pointer => f.write_str("pointer"),
        }
    }
}
impl ::std::str::FromStr for DirectorEnvelopeContentType {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "text" => Ok(Self::Text),
            "task" => Ok(Self::Task),
            "result" => Ok(Self::Result),
            "signal" => Ok(Self::Signal),
            "pointer" => Ok(Self::Pointer),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for DirectorEnvelopeContentType {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for DirectorEnvelopeContentType {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///Optional. The message_id this answers.
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct DirectorEnvelopeInReplyTo(::std::string::String);
impl ::std::ops::Deref for DirectorEnvelopeInReplyTo {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<DirectorEnvelopeInReplyTo> for ::std::string::String {
    fn from(value: DirectorEnvelopeInReplyTo) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for DirectorEnvelopeInReplyTo {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> = ::std::sync::LazyLock::new(||
        { ::regress::Regex::new("^[0-9A-HJKMNP-TV-Z]{26}$").unwrap() });
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^[0-9A-HJKMNP-TV-Z]{26}$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for DirectorEnvelopeInReplyTo {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for DirectorEnvelopeInReplyTo {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for DirectorEnvelopeInReplyTo {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///ULID: sortable, unique. Consumers dedupe on this (delivery is at least once).
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct DirectorEnvelopeMessageId(::std::string::String);
impl ::std::ops::Deref for DirectorEnvelopeMessageId {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<DirectorEnvelopeMessageId> for ::std::string::String {
    fn from(value: DirectorEnvelopeMessageId) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for DirectorEnvelopeMessageId {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> = ::std::sync::LazyLock::new(||
        { ::regress::Regex::new("^[0-9A-HJKMNP-TV-Z]{26}$").unwrap() });
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^[0-9A-HJKMNP-TV-Z]{26}$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for DirectorEnvelopeMessageId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for DirectorEnvelopeMessageId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for DirectorEnvelopeMessageId {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`DirectorEnvelopePerformative`
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd
)]
pub enum DirectorEnvelopePerformative {
    #[serde(rename = "INFORM")]
    Inform,
    #[serde(rename = "REQUEST")]
    Request,
    #[serde(rename = "AGREE")]
    Agree,
    #[serde(rename = "REFUSE")]
    Refuse,
    #[serde(rename = "FAILURE")]
    Failure,
    #[serde(rename = "CFP")]
    Cfp,
    #[serde(rename = "PROPOSE")]
    Propose,
    #[serde(rename = "ACCEPT-PROPOSAL")]
    AcceptProposal,
    #[serde(rename = "REJECT-PROPOSAL")]
    RejectProposal,
    #[serde(rename = "CANCEL")]
    Cancel,
    #[serde(rename = "QUERY")]
    Query,
    #[serde(rename = "NOT-UNDERSTOOD")]
    NotUnderstood,
}
impl ::std::fmt::Display for DirectorEnvelopePerformative {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Inform => f.write_str("INFORM"),
            Self::Request => f.write_str("REQUEST"),
            Self::Agree => f.write_str("AGREE"),
            Self::Refuse => f.write_str("REFUSE"),
            Self::Failure => f.write_str("FAILURE"),
            Self::Cfp => f.write_str("CFP"),
            Self::Propose => f.write_str("PROPOSE"),
            Self::AcceptProposal => f.write_str("ACCEPT-PROPOSAL"),
            Self::RejectProposal => f.write_str("REJECT-PROPOSAL"),
            Self::Cancel => f.write_str("CANCEL"),
            Self::Query => f.write_str("QUERY"),
            Self::NotUnderstood => f.write_str("NOT-UNDERSTOOD"),
        }
    }
}
impl ::std::str::FromStr for DirectorEnvelopePerformative {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "INFORM" => Ok(Self::Inform),
            "REQUEST" => Ok(Self::Request),
            "AGREE" => Ok(Self::Agree),
            "REFUSE" => Ok(Self::Refuse),
            "FAILURE" => Ok(Self::Failure),
            "CFP" => Ok(Self::Cfp),
            "PROPOSE" => Ok(Self::Propose),
            "ACCEPT-PROPOSAL" => Ok(Self::AcceptProposal),
            "REJECT-PROPOSAL" => Ok(Self::RejectProposal),
            "CANCEL" => Ok(Self::Cancel),
            "QUERY" => Ok(Self::Query),
            "NOT-UNDERSTOOD" => Ok(Self::NotUnderstood),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for DirectorEnvelopePerformative {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for DirectorEnvelopePerformative {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///`DirectorEnvelopeRecipient`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct DirectorEnvelopeRecipient {
    ///Where the message goes. role:// resolves to the current holder at delivery; an unresolvable address returns NOT-UNDERSTOOD to the sender.
    pub address: DirectorEnvelopeRecipientAddress,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub team: ::std::option::Option<DirectorEnvelopeRecipientTeam>,
}
///Where the message goes. role:// resolves to the current holder at delivery; an unresolvable address returns NOT-UNDERSTOOD to the sender.
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct DirectorEnvelopeRecipientAddress(::std::string::String);
impl ::std::ops::Deref for DirectorEnvelopeRecipientAddress {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<DirectorEnvelopeRecipientAddress> for ::std::string::String {
    fn from(value: DirectorEnvelopeRecipientAddress) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for DirectorEnvelopeRecipientAddress {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> = ::std::sync::LazyLock::new(||
        {
            ::regress::Regex::new(
                    "^(agent://[a-z0-9][a-z0-9-]{0,31}/[a-z0-9][a-z0-9-]{0,31}|role://[a-z0-9][a-z0-9-]{0,31}/[a-z0-9][a-z0-9-]{0,31}|broadcast://[a-z0-9][a-z0-9-]{0,31}(/[a-z0-9][a-z0-9-]{0,31})?)$",
                )
                .unwrap()
        });
        if PATTERN.find(value).is_none() {
            return Err(
                "doesn't match pattern \"^(agent://[a-z0-9][a-z0-9-]{0,31}/[a-z0-9][a-z0-9-]{0,31}|role://[a-z0-9][a-z0-9-]{0,31}/[a-z0-9][a-z0-9-]{0,31}|broadcast://[a-z0-9][a-z0-9-]{0,31}(/[a-z0-9][a-z0-9-]{0,31})?)$\""
                    .into(),
            );
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for DirectorEnvelopeRecipientAddress {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String>
for DirectorEnvelopeRecipientAddress {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for DirectorEnvelopeRecipientAddress {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`DirectorEnvelopeRecipientTeam`
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct DirectorEnvelopeRecipientTeam(::std::string::String);
impl ::std::ops::Deref for DirectorEnvelopeRecipientTeam {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<DirectorEnvelopeRecipientTeam> for ::std::string::String {
    fn from(value: DirectorEnvelopeRecipientTeam) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for DirectorEnvelopeRecipientTeam {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> = ::std::sync::LazyLock::new(||
        { ::regress::Regex::new("^[a-z0-9][a-z0-9-]{0,31}$").unwrap() });
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^[a-z0-9][a-z0-9-]{0,31}$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for DirectorEnvelopeRecipientTeam {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for DirectorEnvelopeRecipientTeam {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for DirectorEnvelopeRecipientTeam {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`DirectorEnvelopeSender`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct DirectorEnvelopeSender {
    ///The roster address, stable across restarts. Closed character class (R-76): no dot, star, angle bracket, or space, because it is interpolated into a NATS subject (director#3).
    pub agent_id: DirectorEnvelopeSenderAgentId,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub principal: ::std::option::Option<DirectorEnvelopeSenderPrincipal>,
    ///Current role. Informational only, never a routing or authorization input (R-71, R-82).
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub role: ::std::option::Option<::std::string::String>,
    ///The current harness session UUID, the key (R-71). Nullable now; required once marvel sets it at spawn (R-73, R-84). Nothing derives from it yet. The pattern applies only when the value is a string, so null still validates.
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub session: ::std::option::Option<::uuid::Uuid>,
    pub workspace: DirectorEnvelopeSenderWorkspace,
}
///The roster address, stable across restarts. Closed character class (R-76): no dot, star, angle bracket, or space, because it is interpolated into a NATS subject (director#3).
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct DirectorEnvelopeSenderAgentId(::std::string::String);
impl ::std::ops::Deref for DirectorEnvelopeSenderAgentId {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<DirectorEnvelopeSenderAgentId> for ::std::string::String {
    fn from(value: DirectorEnvelopeSenderAgentId) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for DirectorEnvelopeSenderAgentId {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> = ::std::sync::LazyLock::new(||
        { ::regress::Regex::new("^[a-z0-9][a-z0-9-]{0,31}$").unwrap() });
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^[a-z0-9][a-z0-9-]{0,31}$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for DirectorEnvelopeSenderAgentId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for DirectorEnvelopeSenderAgentId {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for DirectorEnvelopeSenderAgentId {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`DirectorEnvelopeSenderPrincipal`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct DirectorEnvelopeSenderPrincipal {
    ///Open. Seeded values: none, launcher.
    pub kind: ::std::string::String,
}
///`DirectorEnvelopeSenderWorkspace`
#[derive(::serde::Serialize, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[serde(transparent)]
pub struct DirectorEnvelopeSenderWorkspace(::std::string::String);
impl ::std::ops::Deref for DirectorEnvelopeSenderWorkspace {
    type Target = ::std::string::String;
    fn deref(&self) -> &::std::string::String {
        &self.0
    }
}
impl ::std::convert::From<DirectorEnvelopeSenderWorkspace> for ::std::string::String {
    fn from(value: DirectorEnvelopeSenderWorkspace) -> Self {
        value.0
    }
}
impl ::std::str::FromStr for DirectorEnvelopeSenderWorkspace {
    type Err = self::error::ConversionError;
    fn from_str(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        static PATTERN: ::std::sync::LazyLock<::regress::Regex> = ::std::sync::LazyLock::new(||
        { ::regress::Regex::new("^[a-z0-9][a-z0-9-]{0,31}$").unwrap() });
        if PATTERN.find(value).is_none() {
            return Err("doesn't match pattern \"^[a-z0-9][a-z0-9-]{0,31}$\"".into());
        }
        Ok(Self(value.to_string()))
    }
}
impl ::std::convert::TryFrom<&str> for DirectorEnvelopeSenderWorkspace {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &str,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for DirectorEnvelopeSenderWorkspace {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl<'de> ::serde::Deserialize<'de> for DirectorEnvelopeSenderWorkspace {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        ::std::string::String::deserialize(deserializer)?
            .parse()
            .map_err(|e: self::error::ConversionError| {
                <D::Error as ::serde::de::Error>::custom(e.to_string())
            })
    }
}
///`DirectorEnvelopeTrace`
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Default)]
#[serde(deny_unknown_fields)]
pub struct DirectorEnvelopeTrace {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub otel_traceparent: ::std::option::Option<::std::string::String>,
}
/// Error types.
pub mod error {
    /// Error from a `TryFrom` or `FromStr` implementation.
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(
            &self,
            f: &mut ::std::fmt::Formatter<'_>,
        ) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
