//! The generator behind `just contracts-gen` and the regeneration guard test.
//! Included by path from both so there is exactly one definition of what the
//! generated file must look like.

/// Header stamped on the generated file. The file is pulled in with
/// `include!` under a `#[rustfmt::skip]` module, so a stray `cargo fmt` cannot
/// rewrite output that the guard test compares verbatim.
pub const HEADER: &str = "// Code generated by `just contracts-gen` from \
contracts/director-envelope.schema.json; DO NOT EDIT.\n\
// The canonical schema lives in ArcavenAE/marvel (see contracts/PINNED.md).\n\n";

/// Generate the Rust source for the envelope types from the schema text.
pub fn generate(schema_json: &str) -> String {
    let schema: schemars::schema::RootSchema =
        serde_json::from_str(schema_json).expect("schema is valid JSON Schema");
    let mut settings = typify::TypeSpaceSettings::default();
    settings.with_struct_builder(false);
    let mut space = typify::TypeSpace::new(&settings);
    space
        .add_root_schema(schema)
        .expect("typify accepts the schema");
    let file = syn::parse2::<syn::File>(space.to_stream()).expect("generated tokens parse");
    format!("{HEADER}{}", prettyplease::unparse(&file))
}
